# Generated by Django 5.2.4 on 2025-07-24 20:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stridesyncapp', '0002_fitbittoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='last_logged_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 7, 24, 20, 23, 45, 277600), null=True),
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_points', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
