# Generated by Django 5.2.3 on 2025-08-02 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stridesyncapp', '0003_alter_streak_last_logged_date_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='streak',
            name='last_logged_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 8, 2, 9, 22, 9, 581366), null=True),
        ),
    ]
