# Generated by Django 5.2.3 on 2025-08-02 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stridesyncapp', '0004_points_total_points_alter_streak_last_logged_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='last_logged_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 8, 2, 6, 55, 1, 956229), null=True),
        ),
    ]
